name: "Setup"
description: "Reusable action to setup the entire build environment"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Installing Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: pnpm

    - name: Install packages
      shell: bash
      run: |
        pnpm install --no-frozen-lockfile

    - name: Install playwright
      shell: bash
      run: |
        pnpm playwright install --with-deps chromium msedge

    - name: Install tauri dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sh <(curl https://create.tauri.app/sh) -y
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

        # install Rust
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Install tauri dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile rustup-init.exe -Uri https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
        .\rustup-init.exe -y
