name: "Setup"
description: "Reusable action to setup the entire build environment"

inputs:
  node-version:
    description: "NodeJS version"
    required: true

env:
  SKIP_YARN_COREPACK_CHECK: 0

runs:
  using: "composite"
  steps:
    - name: Enable corepack
      shell: bash
      run: |
        corepack enable

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"

    - name: Install yarn
      shell: bash
      run: |
        yarn set version stable

    - name: Prerequisites
      shell: bash
      run: |
        yarn install --frozen-lockfile
