name: "Setup"
description: "Reusable action to setup the entire build environment"

inputs:
  node-version:
    description: "NodeJS version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      shell: bash
      run: |
        corepack enable

    - name: Fix yarn
      shell: bash
      run: |
        npm install -g yarn@1.22.19 --force
        yarn set version 4.1.1
        # see https://github.com/yarnpkg/yarn/issues/9015#issuecomment-1831229617

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: "package.json"
        cache: "yarn"

    - name: Prerequisites
      shell: bash
      run: |
        yarn install --frozen-lockfile
