name: "Build and test"

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          #- macos-latest # expensive as fuck

        architecture:
          - x64

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: ./.github/workflows/setup

      - name: Build
        run: |
          yarn turbo build

      - name: Test
        run: |
          yarn turbo test

      - name: Lint
        run: |
          yarn lint

      - name: Format-check
        run: |
          yarn format-check

      - name: Check dependencies
        run: |
          yarn depcheck
