name: "Build and test"

on:
  push:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          #- macos-latest # expensive as fuck

        architecture:
          - x64

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
          token: ${{ secrets.MAVLINK_TS_TOKEN }}
          fetch-depth: 0

      - uses: ./.github/workflows/setup

      - name: Build
        run: |
          pnpm build

      - name: Test
        run: |
          pnpm test

      - name: Lint
        run: |
          pnpm lint

      - name: Format-check
        run: |
          pnpm format-check

      - name: Check dependencies
        run: |
          pnpm depcheck
